### PR TITLE
Update Docker Build

### PR DESCRIPTION
**Pull request by NOXCIS**

### CODE REVIEW

**Comment by jrmi** [comment]
Hey @NOXCIS thanks for your contribution. Before starting the review, could you consider to remove what seems unreladed to the MR like removing the notifications or changing the about page?

**Comment by NOXCIS** [comment]
The Notifications are what cause issue with IOS due to zero support for the Notification API within the OS. I'll try and find some workaround. 

As for the about page. Sure I'm still understanding the structure of darkwire so theres a bit of experimenting with random things.

**Comment by NOXCIS** [comment]
@jrmi I found a workaround for IOS that allows the Notifications API to be used. By Adding "scope": "/", to the maifest.json darkwire can be installed. Which is the only way iOS supports the Notifications API according to the browser compatibility requirements @ https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission_static.

**Comment by jrmi** [comment]
> @jrmi I found a workaround for IOS that allows the Notifications API to be used. By Adding "scope": "/", to the maifest.json darkwire can be installed. Which is the only way iOS supports the Notifications API according to the browser compatibility requirements @ https://developer.mozilla.org/en-US/docs/Web/API/Notification/requestPermission_static.

Great job @NOXCIS I've created a separate MR with just this part if you want to review it. Let me know if it fixes the bug for you. If so, I will merge it so you can remove this part from your MR.

Mind to configure your IDE to automatically add "new line" at the end of the files to prevent unnecessary changes.

By the way I've merged a MR so you might have to rebase your work on the last version ;-)

**Pull request closed without merging**
