### PR TITLE
[i18n] Adds Occitan language

### PR DESCRIPTION
**Pull request by Quenty31**
I hope I made all the changed required.

### CODE REVIEW

**Comment by CutSomeSlack** [comment]
Hello, I'm a translator and pretty new to GitHub. How can I start translating Darkwire into Spanish (ES_ar)? Also, thanks for this useful piece of software :metal:

**Comment by jrmi** [comment]
Hi @CutSomeSlack,

I think you may:
- First create a dedicated issue for that
- Clone the repository, 
- Create a new file `client/src/i18n/es_ar.js` using other files as example
- Propose a PR with this modification
- Since the PR is accepted, the official instance will be public

Do you have enough information ?

**Comment by CutSomeSlack** [comment]
Great list @jrmi. I think it'll do for now. Thank you!

**Comment by devprg** [comment]
Romanian language ( ro.json )

[ro.zip](https://github.com/darkwire/darkwire.io/files/5320462/ro.zip)

**Pull request merged**
