### PR TITLE
Russian translation proposal

### PR DESCRIPTION
**Pull request by yaBobJonez**
I'm a Russian native speaker from Ukraine. Note:
"(-a)" is used as the standard ending in Russian to indicate female gender-specific ending.

### CODE REVIEW

**Comment by jrmi** [comment]
@yaBobJonez just a minor change: you have to add the translation to the `client/src/i18n/index.js` file to enable it.

**Comment by yaBobJonez** [comment]
Okay, I added everything that you requested. I hope it's okay now.

**Comment by yaBobJonez** [comment]
Sorry, I don't know how to fix this...
I have never worked with Circle CI, and I don't know where the problem is.

**Comment by jrmi** [comment]
> I don't know where the problem

**Comment by jrmi** [comment]
> Sorry, I don't know how to fix this...
> I have never worked with Circle CI, and I don't know where the problem is.

Hi,

No problem, I can help you. It's not a CircleCI problem, CircleCi just launch the test command and verify if test pass. You can do the same yourself by executing: `npm run test` inside your development directory. This command execute the same tests and should fails on your computer the same way they fails in CircleCi. 

The problem should be the a non matching snapshot. You can update the snapshot by pressing `u`. (see PR #166 for reference).

**Comment by jrmi** [comment]
I have fixed the problem on PR #173. Do you agree if I close this one and I merge the other PR ?

**Comment by yaBobJonez** [comment]
Oh, sorry for this, everything I've messed up here...
Sure, thank you!

**Comment by jrmi** [comment]
> Oh, sorry for this, everything I've messed up here...
> Sure, thank you!

No problem ;-) 

Thank you again for your contribution and don't hesitate to continue, we learn by doing.

**Pull request closed without merging**
