### PR TITLE
Added Turkish Language (TR)

### PR DESCRIPTION
**Pull request by lilcsz**

### CODE REVIEW

**Comment by lilcsz** [comment]
15 days still not checked????

**Comment by seripap** [comment]
Can you also add this as an option to the app? See #180 on how to do so

**Comment by lilcsz** [comment]
https://github.com/darkwire/darkwire.io/pull/184

**Comment by alanfriedman** [comment]
Thank you @lilcsz. I'll go ahead and merge this and follow up with #184

**Pull request merged**
